### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by jooyoungseo** [mltony/vscode-indent-nav#2]
When I install [the latest release of indent-nav](https://github.com/mltony/vscode-indent-nav/releases/latest/download/indent-nav.vsix) on VSCode insiders. I see the following warning:

FYI, I used command line for extension installation like below:

``` bash
code-insiders --install-extension indent-nav.vsix
```

> Installing extensions...                                                                                                                               
>                     
> (node:4108) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(),
> or Buffer.from()
> methods instead.                                                                                                                                      
>                     
> Extension 'indent-nav.vsix' was successfully installed.                                                                                                
                    
   Although the installation was successful, do you have any plan to address the deprecation warning?

**Comment by mltony** [comment]
Thanks for the tip about installation - I included it in the readme file.

I probably won't fix this - as long as the extension still works. I 
would accept pull requests though.

**Comment by jooyoungseo** [comment]
Okay, I will close this issue then.
