### ISSUE TITLE
Consider publishing to VS marketplace

### ISSUE THREAD

**Issue by isidorn** [mltony/vscode-indent-nav#7]
Hi @mltony please consider publishing your extension to the VS Code marketplace.
That way other users will more easily discover it

This docs should come in handy https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by mltony** [comment]
I published it a while ago under the name indent-nav IIRC. Did it get 
unpublished for some reason?

**Comment by isidorn** [comment]
@mltony ok found it here https://marketplace.visualstudio.com/items?itemName=TonyMalykh.indent-nav

Let's close this issue. Thanks!
